Remove Unused JSON Check
Krutyi-4el/i18nice pull request #33
Opened 2024-01-30 14:03 UTC by colinxu2020

The json module has been added as standard module from python2.4, and the i18nice project targets python3, so checking is json module avaliable is needn't.

2024-01-30 16:04 UTC, Krutyi-4el requested changes
Seems fine, but you haven't updated `translation_tests.py`.

2024-01-31 03:44 UTC, colinxu2020 commented on i18n/config.py
Sorry for forget, I were fixed it in latest commit.

2024-01-31 03:45 UTC, colinxu2020 commented on i18n/loaders/__init__.py
You are right, I was fixed this in latest commit

2024-01-31 07:56 UTC, Krutyi-4el approved these changes

2024-01-31 07:57 UTC, merged